### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by englarm** [NarcissusHliangZhao/Face-Liveness-Detection#1]
svm_minmax_CASIA_REPLAY-ATTACK_with_HSV.txt
svm_model_CASIA_REPLAY-ATTACK_with_HSV

这两个没有，项目无法跑起来，能否提供以下，谢谢。

**Comment by hliangzhao** [comment]
你好。
这两个文件是训练得到的结果，你可以修改main函数进行训练。
训练所使用的数据集有NUAA，CASIA，REPLAY-ATTACK。第一个可以直接下载，后两个需要申请（遵循相关协议），因此很抱歉不能提供给你。
你可以使用NUAA训练得到这两个文件，文件名已经表达出了所使用的数据集以及提取的特征。
